### ISSUE TITLE
Preferences DataStore

### ISSUE THREAD

**Issue by wateralsie** [Team-Smeme/smeem-aos#19]
*Preferences DataStore를 다루기 때문에 Proto 관련 부분은 뺐음

## DataStore란?
* **작고 단순한 데이터**를 (로그인 정보, 다크모드 여부 등 앱 상태나 설정) 저장하는 storage 기법
* Kotlin Coroutines의 Flow 기반 -> 비동기 API 제공, non-blocking
* thread safe - 한 스레드에서 데이터를 이용하여 작업중일 때 다른 스레드가 같은 데이터에 접근x
* data consistency - 다중 스레드 환경에서도 동일한 데이터가 추출될 수 있도록
    * 데이터를 업데이트할 때 Transaction API 사용

### 비동기 vs 동기
* SharedPreferences는 UI 스레드에서 호출하면 스레드를 block하기 때문에 ANR(Application Not Responding - 5초 안으로 사용자의 입력에 응답하지 못해 발생)가 발생할 수 있다
* 반면에 DataStore는 UI 스레드에서 호출해도 내부적으로 `Dispatchers.IO`에서 작업이 이루어지기 때문에 상대적으로 안전하다
### 예외처리
* SharedPreferences는 listener를 쓰지 않는 이상 동기적으로 처리되기 때문에 예외처리가 어렵고, 이 때문에 예상치 못한 에러가 발생할 수 있다
* DataStore는 코루틴을 사용하기 때문에 예외처리가 수월하다
``` Kotlin
// ex)
val text : Flow<String> = context.dataStore.data
        .catch { exception ->
            if (exception is IOException) {
                emit(emptyPreferences())
            } else {
                throw exception
            }
        }
        .map {preferences ->
            preferences[stringKey] ?: ""
        }
```
## Preferences DataStore
* 개념은 SharedPreferences와 거의 동일
* key-value pairs
### 구현 방법
* 앱 전체에서 singleton으로 접근할 수 있도록 해야한다 - top-level에 DataStore 객체를 하나만 만드는 것이 권장된다는 뜻
    * DataStore 객체가 여러개가 되어버리면 data consistency라는 장점을 활용하기 어려움 

1. dependencies 추가
``` Kotlin
dependencies {
        implementation "androidx.datastore:datastore-preferences:1.0.0"
}
```
2. 데이터 읽기
``` Kotlin
val text : Flow<String> = context.dataStore.data
        .catch { e: Throwable ->
            if (e is IOException) {
                // 기타 예외처리
                emit(emptyPreferences())
            } else {
                throw e
            }
        }
        .map {preferences: Preferences ->
            preferences[stringKey] ?: ""
        }
```
3. 데이터 쓰기
``` Kotlin 
suspend fun incrementCounter() {
    try {
        context.dataStore.edit { settings ->
            val currentCounterValue = settings[EXAMPLE_COUNTER] ?: 0
            settings[EXAMPLE_COUNTER] = currentCounterValue + 1
        }
    } catch (e: IOException) {
        // TODO: 예외처리
    }
}
```
[출처](https://developer.android.com/topic/libraries/architecture/datastore#preferences-write)

## 스밈에서는 어떻게 활용할까?
* access, refresh token 저장, refresh token 로직 구성
* 온보딩 마무리 후 일괄적으로 보낼 데이터 저장
    * 어차피 앱 이탈하면 처음으로 돌아가는데 굳이? - 온보딩 마무리 후 넘어갈 데이터가 많고 이 과정에서 거쳐가는 뷰가 많음 putExtra로 계속 넘기는건 비효율적이라고 생각
    * 그럼 앱 이탈하면 데이터는 어캄? - 앱 이탈하는대로(이탈 여부를 어떻게 확인하는지 더 찾아봐야겠지만) 데이터 전체 삭제 

* 일단 여기까지 세팅할 예정

**Comment by daehwan2da** [comment]
#### 필수적으로 담겨야할 데이터
- token
  - accessToken
  - refreshToken
- 익명 사용자의 데이터 
  - room ? or dataStore?

#### "온보딩 마무리 후 일괄적으로 보낼 데이터 저장" 은 안해도 될것같습니다
- 현재는 fragment 로 구성해서 viewmodel 에 담게 구현해두었는데, 이탈 여부에 따른 데이터 보존 기획을 확인해서 dataStore 에 어떻게 저장할지, 언제 파기할지 를 정의해두어야할듯 하네요~
