### ISSUE TITLE
전체적인 네이밍 개편

### ISSUE THREAD

**Issue by wateralsie** [Team-Smeme/smeem-aos#211]
함수, 변수, 클래스 등 전반적으로

**Comment by daehwan2da** [comment]
이거 하고있나요? 배포이후에 수행하면 좋을것같아요

**Comment by wateralsie** [comment]
네네 안그래도 배포 끝나고 여기에 자세한 사항 한번 쓰고 역할분담하고 시작하려고 했어용
나중에 상기시키기 위한 용도로 이슈 미리 올렸슴다
