### ISSUE TITLE
캘린더 전체적인 기기대응 

### ISSUE THREAD

**Issue by haeti-dev** [Team-Smeme/smeem-aos#62]
비율로 할지?

**Comment by daehwan2da** [comment]
캘린더의 크기를 기기에 맞춰 조절할 수 있도록 같이 봐봅시다
- 셀의 크기
- 셀 간 간격 
  - 줄 간격


<img width="498" alt="스크린샷 2023-07-05 오전 12 40 56" src="https://github.com/Team-Smeme/smeem-aos/assets/88091704/70f808c2-5ff3-4e0c-b735-c89a845b9f97">

**Comment by daehwan2da** [comment]
제가 가져갈게요
