### ISSUE TITLE
TimePicker로 시간 설정시 발생하는 버그 수정

### ISSUE THREAD

**Issue by wateralsie** [Team-Smeme/smeem-aos#84]
## *Problems*
* 기기에 따라 타임피커 시간 설정이 30분 간격으로 뜨지 않음
    * 이 타임피커에서 시간 설정시 크래시 발생

## *Todo*
- [x] reflection을 통해 내부 api에 접근하는 대신 다른 방안 모색
- [x] cancel -> 취소 로 변경

<img src="https://github.com/Team-Smeme/smeem-aos/assets/74162198/10c79abc-a2ae-4232-99b2-68928cafe05a" width="300">

**Comment by daehwan2da** [comment]
시간 설정후에 Server API 에 시간값이 담기도록 구현을 하실건가요?
(안되어있으면 제가 할라고합니다)

**Comment by wateralsie** [comment]
@daehwan2da 
타임피커 버그 수정하는데 생각보다 오래걸려서... 이미 변수도 만들어놓은 겸 api 연결해주시면 감사하겠습니다!
`OnboardingVM`에 있는 selectedHour와 selectedMinute으로 선택된 시간 값을 넘겨주면 될 것 같아요
